name: nodejs deploy config

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Create an env file
        run: echo "MONGODB_URL=${{secrets.MONGODB_URL}}" > .env
      - name: Login to Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build a Docker image
        run: docker build -t devbharath21k/nodejs .
      - name: Publish a Docker image
        run: docker push devbharath21k/nodejs:latest
        
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull devbharath21k/nodejs:latest
      - name: Delete old Docker image
        run: docker rmi -f devbharath21k/nodejs:latest
      - name: Run Docker container
        run: docker run -d -p 4000:4000 --name devbharath-nodejs-app-container devbharath21k/nodejs:latest
