name: Deploy node application

on:
  push:
    branches:
      - bharath

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: create an env file
        run: echo "MONGODB_URL=${{secrets.MONGODB_URL}}" > .env
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t devbharath21k/nodejs:tagname .
      - name: Push Docker image to Docker Hub
        run: docker push devbharath21k/nodejs:tagname

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull devbharath21k/nodejs:tagname
      - name: remove running container
        run: docker stop node-app-container || true && docker rm node-app-container || true
      - name: Run Docker container
        run: docker run -d -p 4000:4000 --name devbharath-nodejs-app-container devbharath21k/nodejs:tagname
